"""add github columns to user

Revision ID: ac88bb35026d
Revises: 1a31ce608336
Create Date: 2025-06-27 19:56:31.416965

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ac88bb35026d'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('github_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('github_login', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('github_avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_user_github_id'), 'user', ['github_id'], unique=True)
    op.create_index(op.f('ix_user_github_login'), 'user', ['github_login'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_github_login'), table_name='user')
    op.drop_index(op.f('ix_user_github_id'), table_name='user')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'github_avatar_url')
    op.drop_column('user', 'github_login')
    op.drop_column('user', 'github_id')
    # ### end Alembic commands ###
